### PR TITLE
Update status bar typings - again

### PR DESCRIPTION
**Pull request by akinsho**
@bryphe seems I missed a spot unfortunately so typings were still off just removed the remaining bit

### CODE REVIEW

**Comment by bryphe** [comment]
@Akin909 Ah sorry about that - this actually doesn't need to be updated (it gets generated during the build step). We should remove it from the source and `gitignore` it to avoid confusion!

**Comment by bryphe** [comment]
Opened #8 to remove those

**Comment by akinsho** [comment]
@bryphe ahh understood in which case I'll close this in favour of #8

**Comment by bryphe** [comment]
Cool, sorry you had to spend extra time on this! Closing it out

**Pull request closed without merging**
